<?php
/**
 * Created by PhpStorm.
 * User: phpNT - http://phpnt.com
 * Date: 30.06.2016
 * Time: 22:24
 */

namespace phpnt\yandexMap;

use yii\web\AssetBundle;

class YandexMapsAsset extends AssetBundle
{
    public function init()
    {
        $this->js = [
            'https://api-maps.yandex.ru/2.1-stable/?apikey='.\Yii::$app->params['ymaps_api_key'].'&lang=ru_RU&load=package.map'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
